### ISSUE TITLE
API is dead 😢 

### ISSUE THREAD

**Issue by poma123** [SpiGetOrg/Spiget#16]
It seems like the API is dead in the last few days 😭 
![image](https://user-images.githubusercontent.com/25465545/49048603-a13c1000-f1db-11e8-821a-39059bf4366f.png)

**Comment by Thatsmusic99** [comment]
Does explain a lot for me, since I had someone tell me my updater wasn’t working correctly since it said an older version of my plugin was the “newest”, and I thought it was on my end until I looked twice.

Basically it looks like you can fetch information about a plugin from the API but not the latest updates starting from the 23rd. If you look at the home page as well you’ll notice there’s been “no updated resources since the last update” which I didn’t like the look of much..

**Comment by InventivetalentDev** [comment]
https://api.spiget.org/ is still online. Only the "aqua" server is currently unavailable and traffic is being redirected to a backup server.

**Comment by Thatsmusic99** [comment]
> 
> 
> Okay then, but what's the reason for the the new updates aren't there on the versions list of my plugin?
> I thought it was because the aqua API down
> 
> @Thatsmusic99 same here. :(

I figure the reason why is that the backup server contains all the data the main server had before it went down, although it doesn't fetch any new updates. Which is why the new updates won't be returned, only the old.

> 
> 
> https://api.spiget.org/ is still online. Only the "aqua" server is currently unavailable and traffic is being redirected to a backup server.

Will there be an ETA on when the server will be available again? Judging by your reply, you would've said so if there was, but my best guess is not for now. Regardless, the API has been of massive use to developers like me to help server owners know when we have a new update published, and I can't thank you enough for providing us with the service. And as a matter of fact, thank you for the quick response too, so we do have an idea of what's going on now.

**Comment by InventivetalentDev** [comment]
Found the issue that caused some missing update - it's currently updating what it missed in the past few days & the latest data should be available in the next hour or so :)

**Comment by Thatsmusic99** [comment]
This has definitely improved matters. Thank you!

**Comment by poma123** [comment]
Wow! Thank you, now it's working wonderful! <3
