### ISSUE TITLE
Missing URLs from versions on some resources

### ISSUE THREAD

**Issue by jamesremuscat** [SpiGetOrg/Spiget#5]
https://api.spiget.org/v2/resources/22803/versions doesn't list a URL against any of the available versions.

https://www.spigotmc.org/resources/dragondropelytra.22803/history has download links for all four, so I'm not sure where they went!

The main resource at https://api.spiget.org/v2/resources/22803/ does list a URL under `file`.

In general it's not clear when and which one should use to download a resource:

- The resource's `file.url`
- The `resource/.../download` endpoint
- The URL(s) given in `resource/.../versions`
- The `resource/.../versions/.../download`

Please could you clarify?

**Comment by InventivetalentDev** [comment]
The download URLs for individual versions are usually just `https://www.spigotmc.org/resources/<Resource ID>/download?version=<Version ID>` so it's pretty easy to create those yourself. Although, feel free to submit a pull-request if you want an URL included in the response.  

-`file.url` or the `file` object in general holds information about the resource's download button ("Download Now", which has file size, type and stores the url to the latest version)
- `resources/x/download` downloads the latest version of that resource which was already downloaded and cached by spiget (which is usually a bit complicated due to cloudflare)
- `resources/x/versions/x/download` redirects to the version-download URL I mentioned above, so you could also use that to get a direct link. (Note: These are directly from spigotmc.org and not cached)

**Comment by jamesremuscat** [comment]
Thanks for the clarification. It sounds like, for my use-case, that the `resources/x/versions/x/download` endpoint is the one I want.
